# Generated by Django 5.1.7 on 2025-04-09 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_room_branch'),
        ('app2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Dori nomi')),
                ('dosage', models.CharField(max_length=50, verbose_name='Dozasi')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name="Ko'rsatmalar")),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='app.branch', verbose_name='Filial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Boshlash sanasi')),
                ('end_date', models.DateField(verbose_name='Tugatish sanasi')),
                ('times_per_day', models.JSONField(verbose_name='Kunlik vaqtlar (soatlar)')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ko'rsatmalar")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medicines', to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='app2.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_schedules', to='app.customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_schedules', to='app.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('given_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqt')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_medicines', to=settings.AUTH_USER_MODEL, verbose_name='Hamshira')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app2.medicineschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
