# Generated by Django 5.1.7 on 2025-04-14 17:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_nurseschedule_nurse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseschedule',
            old_name='nurse',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='nurseschedule',
            unique_together={('user', 'day')},
        ),
    ]
