# Generated by Django 5.1.7 on 2025-04-15 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_cabinet_type'),
        ('app2', '0005_rename_nurse_nurseschedule_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Boshlash sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugatish sanasi')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Tashxis')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='app.branch')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='app.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='medicineschedule',
            name='hospitalization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_schedules', to='app2.hospitalization'),
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='hospitalization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='app2.hospitalization'),
        ),
        migrations.CreateModel(
            name='NurseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(verbose_name='Yozuv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospitalization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_notes', to='app2.hospitalization')),
                ('nurse', models.ForeignKey(limit_choices_to={'role': 'nurse'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
