# Generated by Django 5.1.7 on 2025-04-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_meeting_diognosis'),
        ('app2', '0006_hospitalization_medicineschedule_hospitalization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Javob')),
                ('images', models.JSONField(blank=True, default=list, verbose_name="Rasmlar yo'llari")),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='app.branch', verbose_name='Filial')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
