# Generated by Django 5.1.7 on 2025-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='faq_images/', verbose_name='Rasm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='images',
        ),
        migrations.AddField(
            model_name='faq',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='faq_images', to='app2.faqimages', verbose_name='Rasmlar'),
        ),
    ]
