# Generated by Django 5.1.7 on 2025-05-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_contactrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('connected', 'Bog‘lanilgan')], default='new', max_length=20),
        ),
    ]
