# Generated by Django 5.1.7 on 2025-08-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_customerdebt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdebt',
            name='discount_procent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
