# Generated by Django 5.1.7 on 2025-03-12 09:41

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', app.models.CustomUserManager()),
            ],
        ),
    ]
