# Generated by Django 5.1.7 on 2025-03-22 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_clinicnotification_sent_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sent_by',
        ),
        migrations.AddField(
            model_name='notification',
            name='sent_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
