# Generated by Django 5.1.7 on 2025-03-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_notification_sent_to_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('director', 'Director')], default='doctor', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='specialization',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='clinic',
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('neurology', 'Neurology'), ('director', 'Director')], default='general', max_length=20, null=True),
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Xabarnoma', 'verbose_name_plural': 'User Xabarnomalar'},
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
