# Generated by Django 5.1.7 on 2025-03-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cashwithdrawal_meeting_payment_amount_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashwithdrawal',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_withdrawals', to='app.branch'),
        ),
        migrations.AddField(
            model_name='cashwithdrawal',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cash_withdrawals', to='app.clinic'),
            preserve_default=False,
        ),
    ]
