# Generated by Django 5.1.7 on 2025-03-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_branch_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('neurology', 'Neurology'), ('director', 'Director'), ('other', 'Other')], default='general', max_length=20, null=True),
        ),
    ]
