# Generated by Django 5.1.7 on 2025-04-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_task_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clinic_logos/'),
        ),
    ]
