# Generated by Django 5.1.7 on 2025-04-08 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_clinic_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
