# Generated by Django 5.1.7 on 2025-04-08 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_roomhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.branch'),
            preserve_default=False,
        ),
    ]
