# Generated by Django 5.1.7 on 2025-04-13 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_clinic_begin_contract_clinic_end_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='nurse',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'nurse'}, null=True, related_name='nurses', to=settings.AUTH_USER_MODEL),
        ),
    ]
