# Generated by Django 5.1.7 on 2025-04-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_cabinet_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='end_holiday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reason_holiday',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='start_holiday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
