# Generated by Django 5.1.7 on 2025-04-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_user_end_holiday_user_reason_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='organs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='app.cabinet'),
            preserve_default=False,
        ),
    ]
