# Generated by Django 5.1.7 on 2025-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_meeting_organs_meeting_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='type',
            field=models.CharField(choices=[('jarrohlik', 'Jarrohlik'), ('laboratoriya', 'Laboratoriya'), ('tezyordam', 'Tezyordam'), ('stomatalogiya', 'Stomatalogiya'), ('qabulxona', 'Qabulxona')], max_length=100),
        ),
    ]
