# Generated by Django 5.1.7 on 2025-04-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_cabinet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='doctor',
        ),
    ]
