# Generated by Django 5.1.7 on 2025-04-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_customer_birth_date_customer_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='diognosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
