# Generated by Django 5.1.7 on 2025-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_meeting_diognosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_code_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('expected', 'Kutilyapti'), ('accepted', 'Tasdiqlandi'), ('progress', 'Jarayonda'), ('finished', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], max_length=100),
        ),
    ]
