# Generated by Django 5.1.7 on 2025-04-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_meetingfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicnotification',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_notifications', to='app.branch', verbose_name='Filial'),
        ),
    ]
