# Generated by Django 5.1.7 on 2025-05-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='type',
            field=models.CharField(choices=[('jarrohlik', 'Jarrohlik'), ('laboratoriya', 'Laboratoriya'), ('tezyordam', 'Tezyordam'), ('stomatalogiya', 'Stomatalogiya'), ('qabulxona', 'Qabulxona'), ('terapevtik_stomatologiya', 'Terapevtik stomatologiya'), ('ortopedik_stomatologiya', 'Ortopedik stomatologiya'), ('ortodontiya', 'Ortodontiya'), ('xirurgik_stomatologiya', 'Xirurgik stomatologiya'), ('pediatrik_stomatologiya', 'Pediatrik stomatologiya'), ('estetik_stomatologiya', 'Estetik stomatologiya'), ('parodontologiya', 'Parodontologiya'), ('implantologiya', 'Implantologiya'), ('radiologik_stomatologiya', 'Radiologik stomatologiya'), ('profilaktik_stomatologiya', 'Profilaktik stomatologiya')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('neurology', 'Neurology'), ('director', 'Director'), ('stomatology', 'Stomatology'), ('other', 'Other')], default='general', max_length=20, null=True),
        ),
    ]
