# Generated by Django 5.1.7 on 2025-05-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_cabinet_type_alter_user_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='passport_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
