# Generated by Django 5.1.7 on 2025-05-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_customer_email_customer_passport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kpi',
            field=models.DecimalField(decimal_places=2, default=0, help_text='KPI foizda (masalan, 10.00)', max_digits=5),
        ),
    ]
