# Generated by Django 5.1.7 on 2025-06-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_user_kpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='payment_amount',
        ),
        migrations.CreateModel(
            name='DentalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('teeth_number', models.PositiveIntegerField(blank=True, default=1, help_text='Tuzatiladigan tishlar soni', null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_services', to='app.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='dental_services',
            field=models.ManyToManyField(blank=True, null=True, related_name='meetings', to='app.dentalservice'),
        ),
        migrations.CreateModel(
            name='DentalServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_service_categories', to='app.clinic')),
            ],
        ),
        migrations.AddField(
            model_name='dentalservice',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app.dentalservicecategory'),
        ),
    ]
