# Generated by Django 5.1.7 on 2025-05-07 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0030_clinicnotification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise'), ('Trial', 'Trial')], max_length=50)),
                ('storage_limit_gb', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('trial_period_days', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=255)),
                ('issue_description', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('affected_users', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Tekshirilmoqda'), ('in_progress', 'Jarayonda'), ('resolved', 'Hal qilingan')], default='pending', max_length=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_issues', to='app.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.clinic')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_admin.subscriptionplan')),
            ],
        ),
    ]
