# Generated by Django 5.1.7 on 2025-05-09 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_clinicnotification_status'),
        ('custom_admin', '0002_subscriptionplan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiissue',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiissue',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_issues', to='app.clinic'),
        ),
    ]
