# Generated by Django 5.1.7 on 2025-05-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_apiissue_ip_address_alter_apiissue_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiissue',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
