# Generated by Django 5.1.7 on 2025-05-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0004_apiissue_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='discount',
        ),
        migrations.AddField(
            model_name='clinicsubscription',
            name='description_discount',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicsubscription',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
