# Generated by Django 5.1.7 on 2025-05-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0005_remove_subscriptionplan_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='discreption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
