# Generated by Django 5.1.7 on 2025-05-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_clinicnotification_status'),
        ('custom_admin', '0006_subscriptionplan_discreption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.CharField(blank=True, max_length=50, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Tugagan')], default='active', max_length=20)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to='app.clinic')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_admin.subscriptionplan')),
            ],
        ),
    ]
