# Generated by Django 5.1.7 on 2025-05-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0007_clinicsubscriptionhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='discreption',
            new_name='description',
        ),
    ]
