# Generated by Django 5.1.7 on 2025-05-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0008_rename_discreption_subscriptionplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
