# Generated by Django 5.1.7 on 2025-05-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0009_alter_subscriptionplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('expired', 'Tugagan')], default='active', max_length=20),
        ),
    ]
