# Generated by Django 5.1.7 on 2025-05-10 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_clinicnotification_status'),
        ('custom_admin', '0010_clinicsubscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsubscription',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clinic'),
        ),
    ]
