# Generated by Django 5.1.7 on 2025-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0011_alter_clinicsubscription_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsubscription',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='ClinicSubscriptionHistory',
        ),
    ]
