# Generated by Django 5.1.7 on 2025-06-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0012_clinicsubscription_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='admin_limit',
            field=models.PositiveIntegerField(default=1, help_text='Adminlar soni limiti'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='branch_limit',
            field=models.PositiveIntegerField(default=1, help_text='Filiallar soni limiti'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='director_limit',
            field=models.PositiveIntegerField(default=1, help_text='Direktorlar soni limiti'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='doctor_limit',
            field=models.PositiveIntegerField(default=1, help_text='Shifokorlar soni limiti'),
        ),
    ]
