# Generated by Django 5.1.7 on 2025-06-20 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_meeting_payment_amount_dentalservice_and_more'),
        ('custom_admin', '0013_subscriptionplan_admin_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactiveClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('inactive_days', models.PositiveIntegerField(default=7)),
                ('notified', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clinic')),
            ],
        ),
    ]
