# Generated by Django 5.1.7 on 2025-07-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0015_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.CharField(choices=[('yangi', 'Yangi'), ('kutilmoqda', 'Kutilmoqda'), ('aloqada', 'Aloqada'), ('mijozga_aylandi', 'Mijozga aylandi'), ('rad_etildi', 'Rad etildi'), ('telefon_kotarmadi', 'Telefon ko‘tarmadi'), ('keyinroq_qilish', 'Keyinroq telefon qilishni so‘radi'), ('maslahatlashadi', 'Maslahatlashadi'), ('raqam_xato', 'Raqam xato')], default='yangi', max_length=32),
        ),
    ]
