# Generated by Django 5.1.7 on 2025-08-14 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_meeting_payment_amount_dentalservice_and_more'),
        ('custom_admin', '0016_target_comment_target_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='app.customer')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='app.meeting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
