# Generated by Django 5.1.7 on 2025-08-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0017_customerdebt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDebt',
        ),
    ]
